package fr.samlegamer.mcwfencesbyg.block;

import fr.samlegamer.mcwfencesbyg.McwFencesBYG;
import net.kikoz.mcwfences.objects.WiredFence;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.FenceGateBlock;
import net.minecraft.block.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.Identifier;

public class MFBYGBlocksRegistry
{
	public static final Block aspen_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block aspen_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block aspen_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block aspen_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block aspen_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), null, null);
	public static final Block aspen_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), null, null);
	public static final Block baobab_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block baobab_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block baobab_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block baobab_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block baobab_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block baobab_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block blue_enchanted_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block blue_enchanted_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block blue_enchanted_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block blue_enchanted_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block blue_enchanted_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block blue_enchanted_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block cherry_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cherry_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cherry_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cherry_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cherry_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block cherry_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block cika_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cika_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cika_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cika_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cika_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block cika_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block cypress_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cypress_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cypress_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cypress_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block cypress_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block cypress_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block ebony_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ebony_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ebony_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ebony_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ebony_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block ebony_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block ether_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ether_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ether_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ether_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block ether_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block ether_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block fir_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block fir_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block fir_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block fir_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block fir_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block fir_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block green_enchanted_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block green_enchanted_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block green_enchanted_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block green_enchanted_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block green_enchanted_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block green_enchanted_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block holly_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block holly_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block holly_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block holly_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block holly_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block holly_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block jacaranda_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block jacaranda_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block jacaranda_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block jacaranda_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block jacaranda_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block jacaranda_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block lament_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block lament_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block lament_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block lament_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block lament_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block lament_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block mahogany_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block mahogany_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block mahogany_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block mahogany_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block mahogany_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block mahogany_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block white_mangrove_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block white_mangrove_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block white_mangrove_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block white_mangrove_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block white_mangrove_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block white_mangrove_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block maple_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block maple_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block maple_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block maple_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block maple_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block maple_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block nightshade_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block nightshade_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block nightshade_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block nightshade_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block nightshade_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block nightshade_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block palm_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block palm_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block palm_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block palm_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block palm_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block palm_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block pine_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block pine_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block pine_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block pine_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block pine_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block pine_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block rainbow_eucalyptus_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block rainbow_eucalyptus_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block rainbow_eucalyptus_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block rainbow_eucalyptus_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block rainbow_eucalyptus_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block rainbow_eucalyptus_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block redwood_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block redwood_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block redwood_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block redwood_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block redwood_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block redwood_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block skyris_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block skyris_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block skyris_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block skyris_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block skyris_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block skyris_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block willow_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block willow_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block willow_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block willow_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block willow_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block willow_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block witch_hazel_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block witch_hazel_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block witch_hazel_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block witch_hazel_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block witch_hazel_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block witch_hazel_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block zelkova_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block zelkova_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block zelkova_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block zelkova_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block zelkova_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block zelkova_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block bulbis_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block bulbis_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block bulbis_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block bulbis_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block bulbis_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block bulbis_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block imparius_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block imparius_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block imparius_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block imparius_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block imparius_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block imparius_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block sythian_picket_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block sythian_stockade_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block sythian_horse_fence = new FenceBlock(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block sythian_wired_fence = new WiredFence(AbstractBlock.Settings.of(Material.WOOD).strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD));
	public static final Block sythian_highley_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	public static final Block sythian_pyramid_gate = new FenceGateBlock(AbstractBlock.Settings.of(Material.WOOD).nonOpaque().strength(1.5F, 2.5F).sounds(BlockSoundGroup.WOOD), SoundEvents.BLOCK_FENCE_GATE_CLOSE, SoundEvents.BLOCK_FENCE_GATE_OPEN);
	
	public static void registry()
	{
		add("aspen_picket_fence", aspen_picket_fence);
		add("aspen_stockade_fence", aspen_stockade_fence);
		add("aspen_horse_fence", aspen_horse_fence);
		add("aspen_wired_fence", aspen_wired_fence);
		add("aspen_highley_gate", aspen_highley_gate);
		add("aspen_pyramid_gate", aspen_pyramid_gate);
		add("baobab_picket_fence", baobab_picket_fence);
		add("baobab_stockade_fence", baobab_stockade_fence);
		add("baobab_horse_fence", baobab_horse_fence);
		add("baobab_wired_fence", baobab_wired_fence);
		add("baobab_highley_gate", baobab_highley_gate);
		add("baobab_pyramid_gate", baobab_pyramid_gate);
		add("blue_enchanted_picket_fence", blue_enchanted_picket_fence);
		add("blue_enchanted_stockade_fence", blue_enchanted_stockade_fence);
		add("blue_enchanted_horse_fence", blue_enchanted_horse_fence);
		add("blue_enchanted_wired_fence", blue_enchanted_wired_fence);
		add("blue_enchanted_highley_gate", blue_enchanted_highley_gate);
		add("blue_enchanted_pyramid_gate", blue_enchanted_pyramid_gate);
		add("cherry_picket_fence", cherry_picket_fence);
		add("cherry_stockade_fence", cherry_stockade_fence);
		add("cherry_horse_fence", cherry_horse_fence);
		add("cherry_wired_fence", cherry_wired_fence);
		add("cherry_highley_gate", cherry_highley_gate);
		add("cherry_pyramid_gate", cherry_pyramid_gate);
		add("cika_picket_fence", cika_picket_fence);
		add("cika_stockade_fence", cika_stockade_fence);
		add("cika_horse_fence", cika_horse_fence);
		add("cika_wired_fence", cika_wired_fence);
		add("cika_highley_gate", cika_highley_gate);
		add("cika_pyramid_gate", cika_pyramid_gate);
		add("cypress_picket_fence", cypress_picket_fence);
		add("cypress_stockade_fence", cypress_stockade_fence);
		add("cypress_horse_fence", cypress_horse_fence);
		add("cypress_wired_fence", cypress_wired_fence);
		add("cypress_highley_gate", cypress_highley_gate);
		add("cypress_pyramid_gate", cypress_pyramid_gate);
		add("ebony_picket_fence", ebony_picket_fence);
		add("ebony_stockade_fence", ebony_stockade_fence);
		add("ebony_horse_fence", ebony_horse_fence);
		add("ebony_wired_fence", ebony_wired_fence);
		add("ebony_highley_gate", ebony_highley_gate);
		add("ebony_pyramid_gate", ebony_pyramid_gate);
		add("ether_picket_fence", ether_picket_fence);
		add("ether_stockade_fence", ether_stockade_fence);
		add("ether_horse_fence", ether_horse_fence);
		add("ether_wired_fence", ether_wired_fence);
		add("ether_highley_gate", ether_highley_gate);
		add("ether_pyramid_gate", ether_pyramid_gate);
		add("fir_picket_fence", fir_picket_fence);
		add("fir_stockade_fence", fir_stockade_fence);
		add("fir_horse_fence", fir_horse_fence);
		add("fir_wired_fence", fir_wired_fence);
		add("fir_highley_gate", fir_highley_gate);
		add("fir_pyramid_gate", fir_pyramid_gate);
		add("green_enchanted_picket_fence", green_enchanted_picket_fence);
		add("green_enchanted_stockade_fence", green_enchanted_stockade_fence);
		add("green_enchanted_horse_fence", green_enchanted_horse_fence);
		add("green_enchanted_wired_fence", green_enchanted_wired_fence);
		add("green_enchanted_highley_gate", green_enchanted_highley_gate);
		add("green_enchanted_pyramid_gate", green_enchanted_pyramid_gate);
		add("holly_picket_fence", holly_picket_fence);
		add("holly_stockade_fence", holly_stockade_fence);
		add("holly_horse_fence", holly_horse_fence);
		add("holly_wired_fence", holly_wired_fence);
		add("holly_highley_gate", holly_highley_gate);
		add("holly_pyramid_gate", holly_pyramid_gate);
		add("jacaranda_picket_fence", jacaranda_picket_fence);
		add("jacaranda_stockade_fence", jacaranda_stockade_fence);
		add("jacaranda_horse_fence", jacaranda_horse_fence);
		add("jacaranda_wired_fence", jacaranda_wired_fence);
		add("jacaranda_highley_gate", jacaranda_highley_gate);
		add("jacaranda_pyramid_gate", jacaranda_pyramid_gate);
		add("lament_picket_fence", lament_picket_fence);
		add("lament_stockade_fence", lament_stockade_fence);
		add("lament_horse_fence", lament_horse_fence);
		add("lament_wired_fence", lament_wired_fence);
		add("lament_highley_gate", lament_highley_gate);
		add("lament_pyramid_gate", lament_pyramid_gate);
		add("mahogany_picket_fence", mahogany_picket_fence);
		add("mahogany_stockade_fence", mahogany_stockade_fence);
		add("mahogany_horse_fence", mahogany_horse_fence);
		add("mahogany_wired_fence", mahogany_wired_fence);
		add("mahogany_highley_gate", mahogany_highley_gate);
		add("mahogany_pyramid_gate", mahogany_pyramid_gate);
		add("white_mangrove_picket_fence", white_mangrove_picket_fence);
		add("white_mangrove_stockade_fence", white_mangrove_stockade_fence);
		add("white_mangrove_horse_fence", white_mangrove_horse_fence);
		add("white_mangrove_wired_fence", white_mangrove_wired_fence);
		add("white_mangrove_highley_gate", white_mangrove_highley_gate);
		add("white_mangrove_pyramid_gate", white_mangrove_pyramid_gate);
		add("maple_picket_fence", maple_picket_fence);
		add("maple_stockade_fence", maple_stockade_fence);
		add("maple_horse_fence", maple_horse_fence);
		add("maple_wired_fence", maple_wired_fence);
		add("maple_highley_gate", maple_highley_gate);
		add("maple_pyramid_gate", maple_pyramid_gate);
		add("nightshade_picket_fence", nightshade_picket_fence);
		add("nightshade_stockade_fence", nightshade_stockade_fence);
		add("nightshade_horse_fence", nightshade_horse_fence);
		add("nightshade_wired_fence", nightshade_wired_fence);
		add("nightshade_highley_gate", nightshade_highley_gate);
		add("nightshade_pyramid_gate", nightshade_pyramid_gate);
		add("palm_picket_fence", palm_picket_fence);
		add("palm_stockade_fence", palm_stockade_fence);
		add("palm_horse_fence", palm_horse_fence);
		add("palm_wired_fence", palm_wired_fence);
		add("palm_highley_gate", palm_highley_gate);
		add("palm_pyramid_gate", palm_pyramid_gate);
		add("pine_picket_fence", pine_picket_fence);
		add("pine_stockade_fence", pine_stockade_fence);
		add("pine_horse_fence", pine_horse_fence);
		add("pine_wired_fence", pine_wired_fence);
		add("pine_highley_gate", pine_highley_gate);
		add("pine_pyramid_gate", pine_pyramid_gate);
		add("rainbow_eucalyptus_picket_fence", rainbow_eucalyptus_picket_fence);
		add("rainbow_eucalyptus_stockade_fence", rainbow_eucalyptus_stockade_fence);
		add("rainbow_eucalyptus_horse_fence", rainbow_eucalyptus_horse_fence);
		add("rainbow_eucalyptus_wired_fence", rainbow_eucalyptus_wired_fence);
		add("rainbow_eucalyptus_highley_gate", rainbow_eucalyptus_highley_gate);
		add("rainbow_eucalyptus_pyramid_gate", rainbow_eucalyptus_pyramid_gate);
		add("redwood_picket_fence", redwood_picket_fence);
		add("redwood_stockade_fence", redwood_stockade_fence);
		add("redwood_horse_fence", redwood_horse_fence);
		add("redwood_wired_fence", redwood_wired_fence);
		add("redwood_highley_gate", redwood_highley_gate);
		add("redwood_pyramid_gate", redwood_pyramid_gate);
		add("skyris_picket_fence", skyris_picket_fence);
		add("skyris_stockade_fence", skyris_stockade_fence);
		add("skyris_horse_fence", skyris_horse_fence);
		add("skyris_wired_fence", skyris_wired_fence);
		add("skyris_highley_gate", skyris_highley_gate);
		add("skyris_pyramid_gate", skyris_pyramid_gate);
		add("willow_picket_fence", willow_picket_fence);
		add("willow_stockade_fence", willow_stockade_fence);
		add("willow_horse_fence", willow_horse_fence);
		add("willow_wired_fence", willow_wired_fence);
		add("willow_highley_gate", willow_highley_gate);
		add("willow_pyramid_gate", willow_pyramid_gate);
		add("witch_hazel_picket_fence", witch_hazel_picket_fence);
		add("witch_hazel_stockade_fence", witch_hazel_stockade_fence);
		add("witch_hazel_horse_fence", witch_hazel_horse_fence);
		add("witch_hazel_wired_fence", witch_hazel_wired_fence);
		add("witch_hazel_highley_gate", witch_hazel_highley_gate);
		add("witch_hazel_pyramid_gate", witch_hazel_pyramid_gate);
		add("zelkova_picket_fence", zelkova_picket_fence);
		add("zelkova_stockade_fence", zelkova_stockade_fence);
		add("zelkova_horse_fence", zelkova_horse_fence);
		add("zelkova_wired_fence", zelkova_wired_fence);
		add("zelkova_highley_gate", zelkova_highley_gate);
		add("zelkova_pyramid_gate", zelkova_pyramid_gate);
		add("bulbis_picket_fence", bulbis_picket_fence);
		add("bulbis_stockade_fence", bulbis_stockade_fence);
		add("bulbis_horse_fence", bulbis_horse_fence);
		add("bulbis_wired_fence", bulbis_wired_fence);
		add("bulbis_highley_gate", bulbis_highley_gate);
		add("bulbis_pyramid_gate", bulbis_pyramid_gate);
		add("imparius_picket_fence", imparius_picket_fence);
		add("imparius_stockade_fence", imparius_stockade_fence);
		add("imparius_horse_fence", imparius_horse_fence);
		add("imparius_wired_fence", imparius_wired_fence);
		add("imparius_highley_gate", imparius_highley_gate);
		add("imparius_pyramid_gate", imparius_pyramid_gate);
		add("sythian_picket_fence", sythian_picket_fence);
		add("sythian_stockade_fence", sythian_stockade_fence);
		add("sythian_horse_fence", sythian_horse_fence);
		add("sythian_wired_fence", sythian_wired_fence);
		add("sythian_highley_gate", sythian_highley_gate);
		add("sythian_pyramid_gate", sythian_pyramid_gate);
	}
		
	private static void add(String name, Block b)
	{
	    Registry.register(Registries.BLOCK, new Identifier(McwFencesBYG.MODID, name), b);
	    blockItem(b, name);
	}
	    
	private static void blockItem(Block b, String n)
	{
		Registry.register(Registries.ITEM, new Identifier(McwFencesBYG.MODID, n), new BlockItem(b, new Item.Settings()));
	}
}