modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Fences-Compat/issues" #optional

[[mods]] #mandatory
modId="mcwfencesbyg"
version="1.18.2-1.0"
displayName="Macaw's Fences - BYG"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-fences-oh-the-biomes-youll-go"
logoFile="img.png"
credits="sketch_macaw"
authors="Samlegamer"

description='''
Compatibility Oh The Biomes You'll Go with Macaw's Fences for Minecraft 1.18.2.
'''

[[dependencies.mcwfencesbyg]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcwfencesbyg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
