package fr.samlegamer.mcwfencesbop.block;

import fr.samlegamer.mcwfencesbop.McwFencesBOP;
import net.kikoz.mcwfences.objects.FenceHitbox;
import net.kikoz.mcwfences.objects.WiredFence;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.FenceGateBlock;
import net.minecraft.block.WoodType;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class MFBOPBlocksRegistry
{
	private static final AbstractBlock.Settings WOOD = AbstractBlock.Settings.copy(Blocks.OAK_PLANKS);
	private static final AbstractBlock.Settings HEDGES = AbstractBlock.Settings.copy(Blocks.OAK_LEAVES);

	public static final Block dead_picket_fence = new FenceBlock(WOOD);
	public static final Block dead_stockade_fence = new FenceBlock(WOOD);
	public static final Block dead_horse_fence = new FenceBlock(WOOD);
	public static final Block dead_wired_fence = new WiredFence(WOOD);
	public static final Block dead_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block dead_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block fir_picket_fence = new FenceBlock(WOOD);
	public static final Block fir_stockade_fence = new FenceBlock(WOOD);
	public static final Block fir_horse_fence = new FenceBlock(WOOD);
	public static final Block fir_wired_fence = new WiredFence(WOOD);
	public static final Block fir_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block fir_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block hellbark_picket_fence = new FenceBlock(WOOD);
	public static final Block hellbark_stockade_fence = new FenceBlock(WOOD);
	public static final Block hellbark_horse_fence = new FenceBlock(WOOD);
	public static final Block hellbark_wired_fence = new WiredFence(WOOD);
	public static final Block hellbark_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block hellbark_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block jacaranda_picket_fence = new FenceBlock(WOOD);
	public static final Block jacaranda_stockade_fence = new FenceBlock(WOOD);
	public static final Block jacaranda_horse_fence = new FenceBlock(WOOD);
	public static final Block jacaranda_wired_fence = new WiredFence(WOOD);
	public static final Block jacaranda_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block jacaranda_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block magic_picket_fence = new FenceBlock(WOOD);
	public static final Block magic_stockade_fence = new FenceBlock(WOOD);
	public static final Block magic_horse_fence = new FenceBlock(WOOD);
	public static final Block magic_wired_fence = new WiredFence(WOOD);
	public static final Block magic_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block magic_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block mahogany_picket_fence = new FenceBlock(WOOD);
	public static final Block mahogany_stockade_fence = new FenceBlock(WOOD);
	public static final Block mahogany_horse_fence = new FenceBlock(WOOD);
	public static final Block mahogany_wired_fence = new WiredFence(WOOD);
	public static final Block mahogany_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block mahogany_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block palm_picket_fence = new FenceBlock(WOOD);
	public static final Block palm_stockade_fence = new FenceBlock(WOOD);
	public static final Block palm_horse_fence = new FenceBlock(WOOD);
	public static final Block palm_wired_fence = new WiredFence(WOOD);
	public static final Block palm_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block palm_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block redwood_picket_fence = new FenceBlock(WOOD);
	public static final Block redwood_stockade_fence = new FenceBlock(WOOD);
	public static final Block redwood_horse_fence = new FenceBlock(WOOD);
	public static final Block redwood_wired_fence = new WiredFence(WOOD);
	public static final Block redwood_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block redwood_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block umbran_picket_fence = new FenceBlock(WOOD);
	public static final Block umbran_stockade_fence = new FenceBlock(WOOD);
	public static final Block umbran_horse_fence = new FenceBlock(WOOD);
	public static final Block umbran_wired_fence = new WiredFence(WOOD);
	public static final Block umbran_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block umbran_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block willow_picket_fence = new FenceBlock(WOOD);
	public static final Block willow_stockade_fence = new FenceBlock(WOOD);
	public static final Block willow_horse_fence = new FenceBlock(WOOD);
	public static final Block willow_wired_fence = new WiredFence(WOOD);
	public static final Block willow_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block willow_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block empyreal_picket_fence = new FenceBlock(WOOD);
	public static final Block empyreal_stockade_fence = new FenceBlock(WOOD);
	public static final Block empyreal_horse_fence = new FenceBlock(WOOD);
	public static final Block empyreal_wired_fence = new WiredFence(WOOD);
	public static final Block empyreal_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block empyreal_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block maple_picket_fence = new FenceBlock(WOOD);
	public static final Block maple_stockade_fence = new FenceBlock(WOOD);
	public static final Block maple_horse_fence = new FenceBlock(WOOD);
	public static final Block maple_wired_fence = new WiredFence(WOOD);
	public static final Block maple_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block maple_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block pine_picket_fence = new FenceBlock(WOOD);
	public static final Block pine_stockade_fence = new FenceBlock(WOOD);
	public static final Block pine_horse_fence = new FenceBlock(WOOD);
	public static final Block pine_wired_fence = new WiredFence(WOOD);
	public static final Block pine_highley_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block pine_pyramid_gate = new FenceGateBlock(WoodType.OAK, WOOD);
	public static final Block dead_hedge = new FenceHitbox(HEDGES);
	public static final Block fir_hedge = new FenceHitbox(HEDGES);
	public static final Block hellbark_hedge = new FenceHitbox(HEDGES);
	public static final Block jacaranda_hedge = new FenceHitbox(HEDGES);
	public static final Block magic_hedge = new FenceHitbox(HEDGES);
	public static final Block mahogany_hedge = new FenceHitbox(HEDGES);
	public static final Block palm_hedge = new FenceHitbox(HEDGES);
	public static final Block redwood_hedge = new FenceHitbox(HEDGES);
	public static final Block umbran_hedge = new FenceHitbox(HEDGES);
	public static final Block willow_hedge = new FenceHitbox(HEDGES);
	public static final Block empyreal_hedge = new FenceHitbox(HEDGES);
	public static final Block pine_hedge = new FenceHitbox(HEDGES);
	public static final Block orange_maple_hedge = new FenceHitbox(HEDGES);
	public static final Block red_maple_hedge = new FenceHitbox(HEDGES);
	public static final Block yellow_maple_hedge = new FenceHitbox(HEDGES);
	public static final Block cypress_hedge = new FenceHitbox(HEDGES);
	public static final Block snowblossom_hedge = new FenceHitbox(HEDGES);
	public static final Block flowering_oak_hedge = new FenceHitbox(HEDGES);
	public static final Block rainbow_birch_hedge = new FenceHitbox(HEDGES);
	public static final Block origin_hedge = new FenceHitbox(HEDGES);

    public static void registry()
	{
    	add("dead_picket_fence", dead_picket_fence);
    	add("dead_stockade_fence", dead_stockade_fence);
    	add("dead_horse_fence", dead_horse_fence);
    	add("dead_wired_fence", dead_wired_fence);
    	add("dead_highley_gate", dead_highley_gate);
    	add("dead_pyramid_gate", dead_pyramid_gate);
    	add("fir_picket_fence", fir_picket_fence);
    	add("fir_stockade_fence", fir_stockade_fence);
    	add("fir_horse_fence", fir_horse_fence);
    	add("fir_wired_fence", fir_wired_fence);
    	add("fir_highley_gate", fir_highley_gate);
    	add("fir_pyramid_gate", fir_pyramid_gate);
    	add("hellbark_picket_fence", hellbark_picket_fence);
    	add("hellbark_stockade_fence", hellbark_stockade_fence);
    	add("hellbark_horse_fence", hellbark_horse_fence);
    	add("hellbark_wired_fence", hellbark_wired_fence);
    	add("hellbark_highley_gate", hellbark_highley_gate);
    	add("hellbark_pyramid_gate", hellbark_pyramid_gate);
    	add("jacaranda_picket_fence", jacaranda_picket_fence);
    	add("jacaranda_stockade_fence", jacaranda_stockade_fence);
    	add("jacaranda_horse_fence", jacaranda_horse_fence);
    	add("jacaranda_wired_fence", jacaranda_wired_fence);
    	add("jacaranda_highley_gate", jacaranda_highley_gate);
    	add("jacaranda_pyramid_gate", jacaranda_pyramid_gate);
    	add("magic_picket_fence", magic_picket_fence);
    	add("magic_stockade_fence", magic_stockade_fence);
    	add("magic_horse_fence", magic_horse_fence);
    	add("magic_wired_fence", magic_wired_fence);
    	add("magic_highley_gate", magic_highley_gate);
    	add("magic_pyramid_gate", magic_pyramid_gate);
    	add("mahogany_picket_fence", mahogany_picket_fence);
    	add("mahogany_stockade_fence", mahogany_stockade_fence);
    	add("mahogany_horse_fence", mahogany_horse_fence);
    	add("mahogany_wired_fence", mahogany_wired_fence);
    	add("mahogany_highley_gate", mahogany_highley_gate);
    	add("mahogany_pyramid_gate", mahogany_pyramid_gate);
    	add("palm_picket_fence", palm_picket_fence);
    	add("palm_stockade_fence", palm_stockade_fence);
    	add("palm_horse_fence", palm_horse_fence);
    	add("palm_wired_fence", palm_wired_fence);
    	add("palm_highley_gate", palm_highley_gate);
    	add("palm_pyramid_gate", palm_pyramid_gate);
    	add("redwood_picket_fence", redwood_picket_fence);
    	add("redwood_stockade_fence", redwood_stockade_fence);
    	add("redwood_horse_fence", redwood_horse_fence);
    	add("redwood_wired_fence", redwood_wired_fence);
    	add("redwood_highley_gate", redwood_highley_gate);
    	add("redwood_pyramid_gate", redwood_pyramid_gate);
    	add("umbran_picket_fence", umbran_picket_fence);
    	add("umbran_stockade_fence", umbran_stockade_fence);
    	add("umbran_horse_fence", umbran_horse_fence);
    	add("umbran_wired_fence", umbran_wired_fence);
    	add("umbran_highley_gate", umbran_highley_gate);
    	add("umbran_pyramid_gate", umbran_pyramid_gate);
    	add("willow_picket_fence", willow_picket_fence);
    	add("willow_stockade_fence", willow_stockade_fence);
    	add("willow_horse_fence", willow_horse_fence);
    	add("willow_wired_fence", willow_wired_fence);
    	add("willow_highley_gate", willow_highley_gate);
    	add("willow_pyramid_gate", willow_pyramid_gate);
    	add("empyreal_picket_fence", empyreal_picket_fence);
    	add("empyreal_stockade_fence", empyreal_stockade_fence);
    	add("empyreal_horse_fence", empyreal_horse_fence);
    	add("empyreal_wired_fence", empyreal_wired_fence);
    	add("empyreal_highley_gate", empyreal_highley_gate);
    	add("empyreal_pyramid_gate", empyreal_pyramid_gate);
    	add("maple_picket_fence", maple_picket_fence);
    	add("maple_stockade_fence", maple_stockade_fence);
    	add("maple_horse_fence", maple_horse_fence);
    	add("maple_wired_fence", maple_wired_fence);
    	add("maple_highley_gate", maple_highley_gate);
    	add("maple_pyramid_gate", maple_pyramid_gate);
    	add("pine_picket_fence", pine_picket_fence);
    	add("pine_stockade_fence", pine_stockade_fence);
    	add("pine_horse_fence", pine_horse_fence);
    	add("pine_wired_fence", pine_wired_fence);
    	add("pine_highley_gate", pine_highley_gate);
    	add("pine_pyramid_gate", pine_pyramid_gate);
    	add("dead_hedge", dead_hedge);
    	add("fir_hedge", fir_hedge);
    	add("hellbark_hedge", hellbark_hedge);
    	add("jacaranda_hedge", jacaranda_hedge);
    	add("magic_hedge", magic_hedge);
    	add("mahogany_hedge", mahogany_hedge);
    	add("palm_hedge", palm_hedge);
    	add("redwood_hedge", redwood_hedge);
    	add("umbran_hedge", umbran_hedge);
    	add("willow_hedge", willow_hedge);
    	add("empyreal_hedge", empyreal_hedge);
    	add("pine_hedge", pine_hedge);
    	add("orange_maple_hedge", orange_maple_hedge);
    	add("red_maple_hedge", red_maple_hedge);
    	add("yellow_maple_hedge", yellow_maple_hedge);
    	add("cypress_hedge", cypress_hedge);
    	add("snowblossom_hedge", snowblossom_hedge);
    	add("flowering_oak_hedge", flowering_oak_hedge);
    	add("rainbow_birch_hedge", rainbow_birch_hedge);
    	add("origin_hedge", origin_hedge);
	}
    
    private static void add(String name, Block b)
    {
    	Registry.register(Registries.BLOCK, new Identifier(McwFencesBOP.MODID, name), b);
    	blockItem(b, name);
	}
    
    private static void blockItem(Block b, String n)
    {
        Registry.register(Registries.ITEM, new Identifier(McwFencesBOP.MODID, n), new BlockItem(b, new Item.Settings()));
    }
}